version: 0.0
os: linux
files:
  - source: client
    destination: /home/ec2-user/work/qrstack/qr-ui
  - source: /scripts
    destination: /usr/local/codedeployresources
hooks:
  ApplicationStop:
    - location: scripts/application-stop.sh
      timeout: 120
      runas: root
  BeforeInstall:
    - location: scripts/before-install.sh
      timeout: 120
      runas: root
  AfterInstall:
    - location: scripts/after-install.sh
      timeout: 120
      runas: root
  ApplicationStart:
    - location: scripts/application-start.sh
      timeout: 120
      runas: ec2-user
  ValidateService:
    - location: scripts/validate-service.sh
      timeout: 120
      runas: root